name: NanoASC
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip

  # Core training / preprocessing scripts
  - numpy=1.24.3
  - pytorch=1.12.1
  - cudatoolkit=11.6
  - scikit-learn=1.2.2
  - matplotlib-base=3.7.1
  - tqdm=4.65.0

  # Nanopore/BAM/HDF5 data extraction scripts
  - h5py=3.13.0
  - pysam=0.23.3
  - ont-fast5-api=4.1.1
  - ont_vbz_hdf_plugin=1.0.1
  - samtools=1.16.1

  - pip:
      - pod5==0.3.28
